### Module 6 - Stories, maps, and layouts

In [27]:
from vega_datasets import data
import pandas as pd
import altair as alt
import warnings
warnings.filterwarnings('ignore')

In [29]:
movies = data.movies().dropna()
movies.head()

,Title,US_Gross,Worldwide_Gross,US_DVD_Sales,Production_Budget,Release_Date,MPAA_Rating,Running_Time_min,Distributor,Source,Major_Genre,Creative_Type,Director,Rotten_Tomatoes_Rating,IMDB_Rating,IMDB_Votes
1064,12 Rounds,12234694.0,18184083.0,8283859.0,20000000.0,Mar 27 2009,PG-13,108.0,20th Century Fox,Original Screenplay,Action,Contemporary Fiction,Renny Harlin,28.0,5.4,8914.0
1074,2012,166112167.0,766812167.0,50736023.0,200000000.0,Nov 13 2009,PG-13,158.0,Sony Pictures,Original Screenplay,Action,Science Fiction,Roland Emmerich,39.0,6.2,396.0
1090,300,210614939.0,456068181.0,261252400.0,60000000.0,Mar 09 2007,R,117.0,Warner Bros.,Based on Comic/Graphic Novel,Action,Historical Fiction,Zack Snyder,60.0,7.8,235508.0
1095,3:10 to Yuma,53606916.0,69791889.0,51359371.0,48000000.0,Sep 02 2007,R,117.0,Lionsgate,Remake,Western,Historical Fiction,James Mangold,89.0,7.9,98355.0
1107,88 Minutes,16930884.0,32955399.0,11385055.0,30000000.0,Apr 18 2008,R,106.0,Sony Pictures,Original Screenplay,Thriller/Suspense,Contemporary Fiction,Jon Avnet,5.0,5.9,31205.0

### Getting max value

Which movie has the highest budget?

In [30]:
movies[movies['Production_Budget'] == max(movies['Production_Budget'])]

,Title,US_Gross,Worldwide_Gross,US_DVD_Sales,Production_Budget,Release_Date,MPAA_Rating,Running_Time_min,Distributor,Source,Major_Genre,Creative_Type,Director,Rotten_Tomatoes_Rating,IMDB_Rating,IMDB_Votes
2508,Pirates of the Caribbean: At World's End,309420425.0,960996492.0,296060575.0,300000000.0,May 25 2007,PG-13,167.0,Walt Disney Pictures,Disney Ride,Adventure,Fantasy,Gore Verbinski,45.0,7.0,133241.0

What if we want just the title?

In [31]:
movies[movies['Production_Budget'] == max(movies['Production_Budget'])].iloc[0, 0]

"Pirates of the Caribbean: At World's End"

Which movie has the highest box office return?

In [32]:
movies[movies['Worldwide_Gross'] == max(movies['Worldwide_Gross'])].iloc[0, 0]

"Pirates of the Caribbean: Dead Man's Chest"

Try the rest on your own. 

Which is the oldest movie?

Which movie has the most votes on IMDB?

Which movie has the shortest running time?

Most IMDB votes?

There are other methods you can try as well, such as sorting the data on the column of interest, and taking the first (or last) row.

In [33]:
movies.sort_values('Production_Budget').tail(1)

,Title,US_Gross,Worldwide_Gross,US_DVD_Sales,Production_Budget,Release_Date,MPAA_Rating,Running_Time_min,Distributor,Source,Major_Genre,Creative_Type,Director,Rotten_Tomatoes_Rating,IMDB_Rating,IMDB_Votes
2508,Pirates of the Caribbean: At World's End,309420425.0,960996492.0,296060575.0,300000000.0,May 25 2007,PG-13,167.0,Walt Disney Pictures,Disney Ride,Adventure,Fantasy,Gore Verbinski,45.0,7.0,133241.0

In [34]:
movies.sort_values('Production_Budget', ascending=False).head(1)

,Title,US_Gross,Worldwide_Gross,US_DVD_Sales,Production_Budget,Release_Date,MPAA_Rating,Running_Time_min,Distributor,Source,Major_Genre,Creative_Type,Director,Rotten_Tomatoes_Rating,IMDB_Rating,IMDB_Votes
2508,Pirates of the Caribbean: At World's End,309420425.0,960996492.0,296060575.0,300000000.0,May 25 2007,PG-13,167.0,Walt Disney Pictures,Disney Ride,Adventure,Fantasy,Gore Verbinski,45.0,7.0,133241.0

### Assign

What is the profit margin for each movie?

In [35]:
movies['profit'] = movies['US_Gross'] - movies['Production_Budget']
movies

,Title,US_Gross,Worldwide_Gross,US_DVD_Sales,Production_Budget,Release_Date,MPAA_Rating,Running_Time_min,Distributor,Source,Major_Genre,Creative_Type,Director,Rotten_Tomatoes_Rating,IMDB_Rating,IMDB_Votes,profit
1064,12 Rounds,12234694.0,18184083.0,8283859.0,20000000.0,Mar 27 2009,PG-13,108.0,20th Century Fox,Original Screenplay,Action,Contemporary Fiction,Renny Harlin,28.0,5.4,8914.0,-7765306.0
1074,2012,166112167.0,766812167.0,50736023.0,200000000.0,Nov 13 2009,PG-13,158.0,Sony Pictures,Original Screenplay,Action,Science Fiction,Roland Emmerich,39.0,6.2,396.0,-33887833.0
1090,300,210614939.0,456068181.0,261252400.0,60000000.0,Mar 09 2007,R,117.0,Warner Bros.,Based on Comic/Graphic Novel,Action,Historical Fiction,Zack Snyder,60.0,7.8,235508.0,150614939.0
1095,3:10 to Yuma,53606916.0,69791889.0,51359371.0,48000000.0,Sep 02 2007,R,117.0,Lionsgate,Remake,Western,Historical Fiction,James Mangold,89.0,7.9,98355.0,5606916.0
1107,88 Minutes,16930884.0,32955399.0,11385055.0,30000000.0,Apr 18 2008,R,106.0,Sony Pictures,Original Screenplay,Thriller/Suspense,Contemporary Fiction,Jon Avnet,5.0,5.9,31205.0,-13069116.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3158,The Wrestler,26236603.0,43236603.0,11912450.0,6000000.0,Dec 17 2008,R,109.0,Fox Searchlight,Original Screenplay,Drama,Contemporary Fiction,Darren Aronofsky,98.0,8.2,93301.0,20236603.0
3181,Year One,43337279.0,57604723.0,14813995.0,60000000.0,Jun 19 2009,PG-13,97.0,Sony Pictures,Original Screenplay,Comedy,Historical Fiction,Harold Ramis,14.0,5.0,23091.0,-16662721.0
3183,Yes Man,97690976.0,225990976.0,26601131.0,50000000.0,Dec 19 2008,PG-13,104.0,Warner Bros.,Based on Book/Short Story,Comedy,Contemporary Fiction,Peyton Reed,43.0,7.0,62150.0,47690976.0
3195,Zombieland,75590286.0,98690286.0,28281155.0,23600000.0,Oct 02 2009,R,87.0,Sony Pictures,Original Screenplay,Comedy,Fantasy,Ruben Fleischer,89.0,7.8,81629.0,51990286.0
3196,Zack and Miri Make a Porno,31452765.0,36851125.0,21240321.0,24000000.0,Oct 31 2008,R,101.0,Weinstein Co.,Original Screenplay,Comedy,Contemporary Fiction,Kevin Smith,65.0,7.0,55687.0,7452765.0

In [36]:
movies2 = movies.assign(profit = movies['US_Gross'] - movies['Production_Budget'])
movies2.head()

,Title,US_Gross,Worldwide_Gross,US_DVD_Sales,Production_Budget,Release_Date,MPAA_Rating,Running_Time_min,Distributor,Source,Major_Genre,Creative_Type,Director,Rotten_Tomatoes_Rating,IMDB_Rating,IMDB_Votes,profit
1064,12 Rounds,12234694.0,18184083.0,8283859.0,20000000.0,Mar 27 2009,PG-13,108.0,20th Century Fox,Original Screenplay,Action,Contemporary Fiction,Renny Harlin,28.0,5.4,8914.0,-7765306.0
1074,2012,166112167.0,766812167.0,50736023.0,200000000.0,Nov 13 2009,PG-13,158.0,Sony Pictures,Original Screenplay,Action,Science Fiction,Roland Emmerich,39.0,6.2,396.0,-33887833.0
1090,300,210614939.0,456068181.0,261252400.0,60000000.0,Mar 09 2007,R,117.0,Warner Bros.,Based on Comic/Graphic Novel,Action,Historical Fiction,Zack Snyder,60.0,7.8,235508.0,150614939.0
1095,3:10 to Yuma,53606916.0,69791889.0,51359371.0,48000000.0,Sep 02 2007,R,117.0,Lionsgate,Remake,Western,Historical Fiction,James Mangold,89.0,7.9,98355.0,5606916.0
1107,88 Minutes,16930884.0,32955399.0,11385055.0,30000000.0,Apr 18 2008,R,106.0,Sony Pictures,Original Screenplay,Thriller/Suspense,Contemporary Fiction,Jon Avnet,5.0,5.9,31205.0,-13069116.0

What is the profit ratio for each movie?

In [37]:
movies3 = movies2.assign(profit_ratio = movies2['US_Gross'] / movies2['Production_Budget'])
movies3.head()

,Title,US_Gross,Worldwide_Gross,US_DVD_Sales,Production_Budget,Release_Date,MPAA_Rating,Running_Time_min,Distributor,Source,Major_Genre,Creative_Type,Director,Rotten_Tomatoes_Rating,IMDB_Rating,IMDB_Votes,profit,profit_ratio
1064,12 Rounds,12234694.0,18184083.0,8283859.0,20000000.0,Mar 27 2009,PG-13,108.0,20th Century Fox,Original Screenplay,Action,Contemporary Fiction,Renny Harlin,28.0,5.4,8914.0,-7765306.0,0.611735
1074,2012,166112167.0,766812167.0,50736023.0,200000000.0,Nov 13 2009,PG-13,158.0,Sony Pictures,Original Screenplay,Action,Science Fiction,Roland Emmerich,39.0,6.2,396.0,-33887833.0,0.830561
1090,300,210614939.0,456068181.0,261252400.0,60000000.0,Mar 09 2007,R,117.0,Warner Bros.,Based on Comic/Graphic Novel,Action,Historical Fiction,Zack Snyder,60.0,7.8,235508.0,150614939.0,3.510249
1095,3:10 to Yuma,53606916.0,69791889.0,51359371.0,48000000.0,Sep 02 2007,R,117.0,Lionsgate,Remake,Western,Historical Fiction,James Mangold,89.0,7.9,98355.0,5606916.0,1.116811
1107,88 Minutes,16930884.0,32955399.0,11385055.0,30000000.0,Apr 18 2008,R,106.0,Sony Pictures,Original Screenplay,Thriller/Suspense,Contemporary Fiction,Jon Avnet,5.0,5.9,31205.0,-13069116.0,0.564363

In [38]:
profit_ratio_chart = alt.Chart(movies3).mark_circle().encode(
        x=alt.X("Worldwide_Gross"),
    y=alt.Y("profit_ratio"),
    color="Major_Genre"
)

profit_ratio_chart

alt.Chart(...)

In [18]:
### What's the outlier?

movies3[movies3['profit_ratio'] > 6000]

,Title,US_Gross,Worldwide_Gross,US_DVD_Sales,Production_Budget,Release_Date,MPAA_Rating,Running_Time_min,Distributor,Source,Major_Genre,Creative_Type,Director,Rotten_Tomatoes_Rating,IMDB_Rating,IMDB_Votes,profit,profit_ratio
2526,Paranormal Activity,107918810.0,193770453.0,14051496.0,15000.0,2009-09-25,R,85.0,Paramount Pictures,Original Screenplay,Horror,Contemporary Fiction,Oren Peli,82.0,6.7,53455.0,107903810.0,7194.587333

In [19]:
### How does is look with a log scale?

profit_ratio_chart_log = alt.Chart(movies3).mark_circle().encode(
    x=alt.X("Worldwide_Gross"),
    y=alt.Y("profit_ratio", axis=alt.Axis(tickCount=40),
           # scale=alt.Scale(type="log", base=10)
           scale=alt.Scale(type="symlog")
           ),
    tooltip=[
        alt.Tooltip("Title:N"),
        alt.Tooltip('Worldwide_Gross', format='$s'),
        alt.Tooltip("profit_ratio", format='.2f')
                    ]
    # color="Major_Genre"
)

profit_ratio_chart_log

alt.Chart(...)

Stack overflow post: https://stackoverflow.com/questions/3305865/what-is-the-difference-between-log-and-symlog

In [20]:
profit_chart = alt.Chart(movies3).mark_circle().encode(
    x=alt.X("Production_Budget"),
    y=alt.Y("profit"),
    color="Major_Genre"
)

profit_chart

alt.Chart(...)

In [21]:
movies3[(movies3['profit'] > 1500000000)]

Empty DataFrame
Columns: [Title, US_Gross, Worldwide_Gross, US_DVD_Sales, Production_Budget, Release_Date, MPAA_Rating, Running_Time_min, Distributor, Source, Major_Genre, Creative_Type, Director, Rotten_Tomatoes_Rating, IMDB_Rating, IMDB_Votes, profit, profit_ratio]
Index: []

### Merging dataframes

How can we get the counts of each genre in the dataframe?

Step 1: Get the counts of each genre:

In [22]:
genre_counts = movies3.value_counts("Major_Genre")
genre_counts

Major_Genre
Drama                  738
Comedy                 633
Action                 392
Adventure              251
Thriller/Suspense      233
Horror                 209
Romantic Comedy        130
Musical                 50
Documentary             37
Western                 35
Black Comedy            32
Concert/Performance      4
Name: count, dtype: int64

Turn it into a dataframe

In [23]:
genre_counts_df = genre_counts.reset_index()
genre_counts_df

            Major_Genre  count
0                 Drama    738
1                Comedy    633
2                Action    392
3             Adventure    251
4     Thriller/Suspense    233
5                Horror    209
6       Romantic Comedy    130
7               Musical     50
8           Documentary     37
9               Western     35
10         Black Comedy     32
11  Concert/Performance      4

In [24]:
genre_counts_df.columns =['a', 'b']
genre_counts_df

                      a    b
0                 Drama  738
1                Comedy  633
2                Action  392
3             Adventure  251
4     Thriller/Suspense  233
5                Horror  209
6       Romantic Comedy  130
7               Musical   50
8           Documentary   37
9               Western   35
10         Black Comedy   32
11  Concert/Performance    4

Rename the columns

In [25]:
genre_counts_df.columns = ['Major_Genre', 'Genre_counts']
# genre_counts_df = genre_counts_df[genre_counts_df['Genre']=="Drama"]
genre_counts_df

            Major_Genre  Genre_counts
0                 Drama           738
1                Comedy           633
2                Action           392
3             Adventure           251
4     Thriller/Suspense           233
5                Horror           209
6       Romantic Comedy           130
7               Musical            50
8           Documentary            37
9               Western            35
10         Black Comedy            32
11  Concert/Performance             4

Merge with original dataframe

In [26]:
movies_full = movies3.merge(genre_counts_df,
                           on='Major_Genre',
                           # right_on='Genre',
                           how='left')

movies_full.head(10)

,Title,US_Gross,Worldwide_Gross,US_DVD_Sales,Production_Budget,Release_Date,MPAA_Rating,Running_Time_min,Distributor,Source,Major_Genre,Creative_Type,Director,Rotten_Tomatoes_Rating,IMDB_Rating,IMDB_Votes,profit,profit_ratio,Genre_counts
0,The Land Girls,146083.0,146083.0,NaN,8000000.0,1998-06-12,R,NaN,Gramercy,None,None,None,None,NaN,6.1,1071.0,-7853917.0,0.018260,NaN
1,"First Love, Last Rites",10876.0,10876.0,NaN,300000.0,1998-08-07,R,NaN,Strand,None,Drama,None,None,NaN,6.9,207.0,-289124.0,0.036253,738.0
2,I Married a Strange Person,203134.0,203134.0,NaN,250000.0,1998-08-28,None,NaN,Lionsgate,None,Comedy,None,None,NaN,6.8,865.0,-46866.0,0.812536,633.0
3,Slam,1009819.0,1087521.0,NaN,1000000.0,1998-10-09,R,NaN,Trimark,Original Screenplay,Drama,Contemporary Fiction,None,62.0,3.4,165.0,9819.0,1.009819,738.0
4,Following,44705.0,44705.0,NaN,6000.0,1999-04-04,R,NaN,Zeitgeist,None,None,None,Christopher Nolan,NaN,7.7,15133.0,38705.0,7.450833,NaN
5,Foolish,6026908.0,6026908.0,NaN,1600000.0,1999-04-09,R,NaN,Artisan,Original Screenplay,Comedy,Contemporary Fiction,None,NaN,3.8,353.0,4426908.0,3.766818,633.0
6,Pirates,1641825.0,6341825.0,NaN,40000000.0,1986-07-01,R,NaN,None,None,None,None,Roman Polanski,25.0,5.8,3275.0,-38358175.0,0.041046,NaN
7,Duel in the Sun,20400000.0,20400000.0,NaN,6000000.0,2046-12-31,None,NaN,None,None,None,None,None,86.0,7.0,2906.0,14400000.0,3.400000,NaN
8,Tom Jones,37600000.0,37600000.0,NaN,1000000.0,1963-10-07,None,NaN,None,None,None,None,None,81.0,7.0,4035.0,36600000.0,37.600000,NaN
9,Oliver!,37402877.0,37402877.0,NaN,10000000.0,1968-12-11,None,NaN,Sony Pictures,None,Musical,None,None,84.0,7.5,9111.0,27402877.0,3.740288,50.0

In [27]:
# How many rows did we get?

movies_full.shape[0]

2982

In [28]:
# How many in our original data?

movies3.shape[0]

2982

In [29]:
movies3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2982 entries, 0 to 3200
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Title                   2981 non-null   object
 1   US_Gross                2982 non-null   float64
 2   Worldwide_Gross         2982 non-null   float64
 3   US_DVD_Sales            529 non-null    float64
 4   Production_Budget       2982 non-null   float64
 5   Release_Date            2982 non-null   datetime64[ns]
 6   MPAA_Rating             2428 non-null   object
 7   Running_Time_min        1145 non-null   float64
 8   Distributor             2785 non-null   object
 9   Source                  2665 non-null   object
 10  Major_Genre             2744 non-null   object
 11  Creative_Type           2593 non-null   object
 12  Director                1774 non-null   object
 13  Rotten_Tomatoes_Rating  2255 non-null   float64
 14  IMDB_Rating             2982 non-null   float64
 15  IMDB_Votes              2982 non-null   float64
 16  profit                  2982 non-null   float64
 17  profit_ratio            2982 non-null   float64
dtypes: datetime64[ns](1), float64(10), object(7)
memory usage: 442.6+ KB

What are the arguments for merge?

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.merge.html

![img](https://cdn.educba.com/academy/wp-content/uploads/2019/10/Types-of-Join-inSQL.jpg.webp)

In [30]:
2982*12

35784

In [31]:
genre_counts_df.merge(movies3, 
                      how='cross')

,Major_Genre_x,Genre_counts,Title,US_Gross,Worldwide_Gross,US_DVD_Sales,Production_Budget,Release_Date,MPAA_Rating,Running_Time_min,Distributor,Source,Major_Genre_y,Creative_Type,Director,Rotten_Tomatoes_Rating,IMDB_Rating,IMDB_Votes,profit,profit_ratio
0,Drama,738,The Land Girls,146083.0,146083.0,NaN,8000000.0,1998-06-12,R,NaN,Gramercy,None,None,None,None,NaN,6.1,1071.0,-7853917.0,0.018260
1,Drama,738,"First Love, Last Rites",10876.0,10876.0,NaN,300000.0,1998-08-07,R,NaN,Strand,None,Drama,None,None,NaN,6.9,207.0,-289124.0,0.036253
2,Drama,738,I Married a Strange Person,203134.0,203134.0,NaN,250000.0,1998-08-28,None,NaN,Lionsgate,None,Comedy,None,None,NaN,6.8,865.0,-46866.0,0.812536
3,Drama,738,Slam,1009819.0,1087521.0,NaN,1000000.0,1998-10-09,R,NaN,Trimark,Original Screenplay,Drama,Contemporary Fiction,None,62.0,3.4,165.0,9819.0,1.009819
4,Drama,738,Following,44705.0,44705.0,NaN,6000.0,1999-04-04,R,NaN,Zeitgeist,None,None,None,Christopher Nolan,NaN,7.7,15133.0,38705.0,7.450833
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35779,Concert/Performance,4,Zombieland,75590286.0,98690286.0,28281155.0,23600000.0,2009-10-02,R,87.0,Sony Pictures,Original Screenplay,Comedy,Fantasy,Ruben Fleischer,89.0,7.8,81629.0,51990286.0,3.202978
35780,Concert/Performance,4,Zack and Miri Make a Porno,31452765.0,36851125.0,21240321.0,24000000.0,2008-10-31,R,101.0,Weinstein Co.,Original Screenplay,Comedy,Contemporary Fiction,Kevin Smith,65.0,7.0,55687.0,7452765.0,1.310532
35781,Concert/Performance,4,Zoom,11989328.0,12506188.0,6679409.0,35000000.0,2006-08-11,PG,NaN,Sony Pictures,Based on Comic/Graphic Novel,Adventure,Super Hero,Peter Hewitt,3.0,3.4,7424.0,-23010672.0,0.342552
35782,Concert/Performance,4,The Legend of Zorro,45575336.0,141475336.0,NaN,80000000.0,2005-10-28,PG,129.0,Sony Pictures,Remake,Adventure,Historical Fiction,Martin Campbell,26.0,5.7,21161.0,-34424664.0,0.569692
35783,Concert/Performance,4,The Mask of Zorro,93828745.0,233700000.0,NaN,65000000.0,1998-07-17,PG-13,136.0,Sony Pictures,Remake,Adventure,Historical Fiction,Martin Campbell,82.0,6.7,4789.0,28828745.0,1.443519

In [32]:
# Why so many rows?

3200*12

38400

In [33]:
### How does pandas find the common column name?

m3_cols = set(movies3.columns)
m3_cols

{'Creative_Type',
 'Director',
 'Distributor',
 'IMDB_Rating',
 'IMDB_Votes',
 'MPAA_Rating',
 'Major_Genre',
 'Production_Budget',
 'Release_Date',
 'Rotten_Tomatoes_Rating',
 'Running_Time_min',
 'Source',
 'Title',
 'US_DVD_Sales',
 'US_Gross',
 'Worldwide_Gross',
 'profit',
 'profit_ratio'}

In [34]:
gc_cols = set(genre_counts_df.columns)
gc_cols

{'Genre_counts', 'Major_Genre'}

In [35]:
gc_cols.intersection(m3_cols)

{'Major_Genre'}

In [36]:
### What if your dataframes have different column names?

genre_counts_df.columns = ['Genre', 'Genre count']
genre_counts_df

                  Genre  Genre count
0                 Drama          738
1                Comedy          633
2                Action          392
3             Adventure          251
4     Thriller/Suspense          233
5                Horror          209
6       Romantic Comedy          130
7               Musical           50
8           Documentary           37
9               Western           35
10         Black Comedy           32
11  Concert/Performance            4

In [37]:
movies_full = movies3.merge(genre_counts_df, left_on='Major_Genre', right_on='Genre')
movies_full

,Title,US_Gross,Worldwide_Gross,US_DVD_Sales,Production_Budget,Release_Date,MPAA_Rating,Running_Time_min,Distributor,Source,Major_Genre,Creative_Type,Director,Rotten_Tomatoes_Rating,IMDB_Rating,IMDB_Votes,profit,profit_ratio,Genre,Genre count
0,"First Love, Last Rites",10876.0,10876.0,NaN,300000.0,1998-08-07,R,NaN,Strand,None,Drama,None,None,NaN,6.9,207.0,-289124.0,0.036253,Drama,738
1,I Married a Strange Person,203134.0,203134.0,NaN,250000.0,1998-08-28,None,NaN,Lionsgate,None,Comedy,None,None,NaN,6.8,865.0,-46866.0,0.812536,Comedy,633
2,Slam,1009819.0,1087521.0,NaN,1000000.0,1998-10-09,R,NaN,Trimark,Original Screenplay,Drama,Contemporary Fiction,None,62.0,3.4,165.0,9819.0,1.009819,Drama,738
3,Foolish,6026908.0,6026908.0,NaN,1600000.0,1999-04-09,R,NaN,Artisan,Original Screenplay,Comedy,Contemporary Fiction,None,NaN,3.8,353.0,4426908.0,3.766818,Comedy,633
4,Oliver!,37402877.0,37402877.0,NaN,10000000.0,1968-12-11,None,NaN,Sony Pictures,None,Musical,None,None,84.0,7.5,9111.0,27402877.0,3.740288,Musical,50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2739,Zombieland,75590286.0,98690286.0,28281155.0,23600000.0,2009-10-02,R,87.0,Sony Pictures,Original Screenplay,Comedy,Fantasy,Ruben Fleischer,89.0,7.8,81629.0,51990286.0,3.202978,Comedy,633
2740,Zack and Miri Make a Porno,31452765.0,36851125.0,21240321.0,24000000.0,2008-10-31,R,101.0,Weinstein Co.,Original Screenplay,Comedy,Contemporary Fiction,Kevin Smith,65.0,7.0,55687.0,7452765.0,1.310532,Comedy,633
2741,Zoom,11989328.0,12506188.0,6679409.0,35000000.0,2006-08-11,PG,NaN,Sony Pictures,Based on Comic/Graphic Novel,Adventure,Super Hero,Peter Hewitt,3.0,3.4,7424.0,-23010672.0,0.342552,Adventure,251
2742,The Legend of Zorro,45575336.0,141475336.0,NaN,80000000.0,2005-10-28,PG,129.0,Sony Pictures,Remake,Adventure,Historical Fiction,Martin Campbell,26.0,5.7,21161.0,-34424664.0,0.569692,Adventure,251
2743,The Mask of Zorro,93828745.0,233700000.0,NaN,65000000.0,1998-07-17,PG-13,136.0,Sony Pictures,Remake,Adventure,Historical Fiction,Martin Campbell,82.0,6.7,4789.0,28828745.0,1.443519,Adventure,251

### Sort a chart using unrelated metric

In [38]:
### I want to show average profit by genre, but sort it by the count of films in each genre.

genre_counts

Major_Genre
Drama                  738
Comedy                 633
Action                 392
Adventure              251
Thriller/Suspense      233
Horror                 209
Romantic Comedy        130
Musical                 50
Documentary             37
Western                 35
Black Comedy            32
Concert/Performance      4
Name: count, dtype: int64

In [39]:
genre_list = genre_counts.index.to_list()
genre_list

['Drama',
 'Comedy',
 'Action',
 'Adventure',
 'Thriller/Suspense',
 'Horror',
 'Romantic Comedy',
 'Musical',
 'Documentary',
 'Western',
 'Black Comedy',
 'Concert/Performance']

In [40]:
genre_profit_chart = alt.Chart(movies3).mark_bar().encode(
    x = alt.X('mean(profit)'),
    y = alt.Y('Major_Genre',
              sort=genre_list)
)

genre_profit_chart

alt.Chart(...)

### Maps

In [56]:
## From module 7

world_map = alt.topo_feature(data.world_110m.url, 'countries')

alt.Chart(world_map).mark_geoshape()

alt.Chart(...)

### Breaking it down
https://github.com/vega/vega-datasets/tree/main/data

In [58]:
world_map_data = data.world_110m.url
world_map_data

'https://cdn.jsdelivr.net/npm/vega-datasets@v1.29.0/data/world-110m.json'

In [64]:
world_map = alt.topo_feature(world_map_data, 'countries')
# world_map = alt.topo_feature(data.world_110m.url, 'land')

world_map

UrlData({
  format: TopoDataFormat({
    feature: 'countries',
    type: 'topojson'
  }),
  url: 'https://cdn.jsdelivr.net/npm/vega-datasets@v1.29.0/data/world-110m.json'
})

In [68]:
alt.Chart(world_map).mark_geoshape()

alt.Chart(...)

In [46]:
alt.Chart(world_map).mark_geoshape().project('mercator')

### Projection types: ['albers', 'albersUsa', 'azimuthalEqualArea', 'azimuthalEquidistant', 
### 'conicConformal', 'conicEqualArea', 'conicEquidistant', 'equalEarth', 'equirectangular', 
### 'gnomonic', 'identity', 'mercator', 'naturalEarth1', 'orthographic', 'stereographic', 'transverseMercator']

alt.Chart(...)

In [47]:
alt.Chart(world_map).mark_geoshape(stroke='black',
                                  strokeWidth=0.5).project('naturalEarth1',
                                                           scale=100)

alt.Chart(...)

More projections:

https://vega.github.io/vega/docs/projections/

In [48]:
data.us_10m.url

'https://cdn.jsdelivr.net/npm/vega-datasets@v1.29.0/data/us-10m.json'

### Adding info to map

In [49]:
state_map = alt.topo_feature(data.us_10m.url, 'states')
alt.Chart(state_map).mark_geoshape().encode(color='id:Q').project(type='albersUsa')

alt.Chart(...)

In [50]:
income =  data.income()
income

            name region  id    pct    total             group
0        Alabama  south   1  0.102  1837292            <10000
1        Alabama  south   1  0.072  1837292    10000 to 14999
2        Alabama  south   1  0.130  1837292    15000 to 24999
3        Alabama  south   1  0.115  1837292    25000 to 34999
4        Alabama  south   1  0.143  1837292    35000 to 49999
..           ...    ...  ..    ...      ...               ...
515  Puerto Rico  other  72  0.035  1254274    75000 to 99999
516  Puerto Rico  other  72  0.094  1254274    50000 to 74999
517  Puerto Rico  other  72  0.024  1254274  100000 to 149999
518  Puerto Rico  other  72  0.008  1254274  150000 to 199999
519  Puerto Rico  other  72  0.006  1254274           200000+

[520 rows x 6 columns]

In [73]:
alt.Chart(state_map).mark_geoshape(
).transform_lookup(
    lookup='id',
    from_=alt.LookupData(income, 'id', ['pct', 'name', 'region'])
).encode(color='pct:Q',
        tooltip=['name:N', 'region:N']).project(type='albersUsa')

alt.Chart(...)